/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gustavofosu.viewAndController;

import com.gustavofosu.model.OrderProcessing;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextArea;

/**
 *
 * @author Honor
 */
public class MainMenu extends javax.swing.JFrame {

    private static final OrderProcessing orderProcess = new OrderProcessing();
    private static int Qty1, Qty2, Qty3, Qty4, Qty5;
    private static String sub1, sub2, sub3, sub4, sub5, subTotal, delivery, netTotal;
    private static Calendar calendar;
    private static SimpleDateFormat simpleDateFormat, simpleTimeFormat;
    
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        if (Login_fds.customerDetails.getMiddleName() == null) {
            JLblCustomerName.setText(Login_fds.customerDetails.getFirstName() + " "
                    + Login_fds.customerDetails.getLastName());
        } else {
            JLblCustomerName.setText(Login_fds.customerDetails.getFullName());
        }
        JLblCustomerAddress.setText(Login_fds.customerDetails.getAddress());
        JLblCustomerPhoneNumber.setText(Login_fds.customerDetails.getPhoneNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLblName = new javax.swing.JLabel();
        JLblAddress = new javax.swing.JLabel();
        jLblOrderTime = new javax.swing.JLabel();
        jLblOrderDate = new javax.swing.JLabel();
        jLblPhoneNo = new javax.swing.JLabel();
        jtxtOrderDate = new javax.swing.JTextField();
        jtxtOrderTime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JLblCustomerName = new javax.swing.JLabel();
        JLblCustomerAddress = new javax.swing.JLabel();
        JLblCustomerPhoneNumber = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLblUnitPrice = new javax.swing.JLabel();
        jLblFC = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLblItemType1 = new javax.swing.JLabel();
        jLblQty = new javax.swing.JLabel();
        jLblSubTotal = new javax.swing.JLabel();
        jtxtFCSubTotal = new javax.swing.JTextField();
        jtxtFECSubTotal = new javax.swing.JTextField();
        jtxtFCUnitPrice = new javax.swing.JTextField();
        jtxtFECUnitPrice = new javax.swing.JTextField();
        jtxtFsCUnitPrice = new javax.swing.JTextField();
        jtxtFsCSubTotal = new javax.swing.JTextField();
        jtxtFCQty = new javax.swing.JTextField();
        jtxtFECQty = new javax.swing.JTextField();
        jtxtFsCQty = new javax.swing.JTextField();
        jLblFEC = new javax.swing.JLabel();
        jLblJC = new javax.swing.JLabel();
        jLblJEC = new javax.swing.JLabel();
        jtxtJECQty = new javax.swing.JTextField();
        jtxtJECUnitPrice = new javax.swing.JTextField();
        jtxtJECSubTotal = new javax.swing.JTextField();
        jLblFsC = new javax.swing.JLabel();
        jtxtJCQty = new javax.swing.JTextField();
        jtxtJCUnitPrice = new javax.swing.JTextField();
        jtxtJCSubTotal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLblOrderTotal = new javax.swing.JLabel();
        jLblDeliveryFee = new javax.swing.JLabel();
        jtxtOrderTotal = new javax.swing.JTextField();
        jtxtDeliveryFee = new javax.swing.JTextField();
        jLblNetPrice = new javax.swing.JLabel();
        jtxtNetPrice = new javax.swing.JTextField();
        jBtnSubmit = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jLblTitle = new javax.swing.JLabel();
        jBtnConfirm = new javax.swing.JButton();
        jBtnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 210));

        JLblName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLblName.setForeground(new java.awt.Color(255, 255, 255));
        JLblName.setText("Customer Name:");

        JLblAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLblAddress.setForeground(new java.awt.Color(255, 255, 255));
        JLblAddress.setText("Customer Address:");

        jLblOrderTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblOrderTime.setForeground(new java.awt.Color(255, 255, 255));
        jLblOrderTime.setText("Order Time:");

        jLblOrderDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblOrderDate.setForeground(new java.awt.Color(255, 255, 255));
        jLblOrderDate.setText("Order Date:");

        jLblPhoneNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblPhoneNo.setForeground(new java.awt.Color(255, 255, 255));
        jLblPhoneNo.setText("Customer Phone No:");

        jtxtOrderDate.setEditable(false);
        jtxtOrderDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtOrderDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtOrderDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtOrderTime.setEditable(false);
        jtxtOrderTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtOrderTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtOrderTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Customer Details");

        JLblCustomerName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLblCustomerName.setForeground(new java.awt.Color(255, 255, 255));

        JLblCustomerAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLblCustomerAddress.setForeground(new java.awt.Color(255, 255, 255));

        JLblCustomerPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLblCustomerPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLblName)
                    .addComponent(JLblAddress)
                    .addComponent(jLblPhoneNo))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLblCustomerPhoneNumber)
                    .addComponent(JLblCustomerName)
                    .addComponent(JLblCustomerAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblOrderDate)
                    .addComponent(jLblOrderTime))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtOrderDate, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jtxtOrderTime))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblOrderDate)
                            .addComponent(jtxtOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblOrderTime)
                            .addComponent(jtxtOrderTime, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblName)
                            .addComponent(JLblCustomerName))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblAddress)
                            .addComponent(JLblCustomerAddress))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblPhoneNo)
                            .addComponent(JLblCustomerPhoneNumber))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLblUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblUnitPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLblUnitPrice.setText("Unit Price");

        jLblFC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLblFC.setForeground(new java.awt.Color(255, 255, 255));
        jLblFC.setText("Fried Rice & Chicken");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Order Processing");

        jLblItemType1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblItemType1.setForeground(new java.awt.Color(255, 255, 255));
        jLblItemType1.setText("Food Type");

        jLblQty.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblQty.setForeground(new java.awt.Color(255, 255, 255));
        jLblQty.setText("Qty");

        jLblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLblSubTotal.setText("Sub-Total");

        jtxtFCSubTotal.setEditable(false);
        jtxtFCSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFCSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFCSubTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtFECSubTotal.setEditable(false);
        jtxtFECSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFECSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFECSubTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtFCUnitPrice.setEditable(false);
        jtxtFCUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFCUnitPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFCUnitPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtFECUnitPrice.setEditable(false);
        jtxtFECUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFECUnitPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFECUnitPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtFsCUnitPrice.setEditable(false);
        jtxtFsCUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFsCUnitPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFsCUnitPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtFsCSubTotal.setEditable(false);
        jtxtFsCSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFsCSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFsCSubTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtFCQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFCQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFCQty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtFECQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFECQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFECQty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtFsCQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFsCQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFsCQty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLblFEC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLblFEC.setForeground(new java.awt.Color(255, 255, 255));
        jLblFEC.setText("Fried Rice, Egg & Chicken");

        jLblJC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLblJC.setForeground(new java.awt.Color(255, 255, 255));
        jLblJC.setText("Fries & Chicken");

        jLblJEC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLblJEC.setForeground(new java.awt.Color(255, 255, 255));
        jLblJEC.setText("Jollof Rice, Egg & Chicken");

        jtxtJECQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtJECQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtJECQty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtJECUnitPrice.setEditable(false);
        jtxtJECUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtJECUnitPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtJECUnitPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtJECSubTotal.setEditable(false);
        jtxtJECSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtJECSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtJECSubTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLblFsC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLblFsC.setForeground(new java.awt.Color(255, 255, 255));
        jLblFsC.setText("Jollof Rice & Chicken");

        jtxtJCQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtJCQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtJCQty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtJCUnitPrice.setEditable(false);
        jtxtJCUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtJCUnitPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtJCUnitPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtJCSubTotal.setEditable(false);
        jtxtJCSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtJCSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtJCSubTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblFC)
                            .addComponent(jLblItemType1)
                            .addComponent(jLblFEC)
                            .addComponent(jLblJC)
                            .addComponent(jLblJEC)
                            .addComponent(jLblFsC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtFCQty)
                            .addComponent(jLblQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtFECQty)
                            .addComponent(jtxtFsCQty)
                            .addComponent(jtxtJECQty)
                            .addComponent(jtxtJCQty))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtFCUnitPrice)
                            .addComponent(jLblUnitPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtFECUnitPrice)
                            .addComponent(jtxtFsCUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtJECUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtJCUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtFECSubTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtFCSubTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtFsCSubTotal)
                            .addComponent(jtxtJECSubTotal)
                            .addComponent(jtxtJCSubTotal))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblUnitPrice)
                    .addComponent(jLblQty)
                    .addComponent(jLblItemType1)
                    .addComponent(jLblSubTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFCSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFCUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFCQty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblFC))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFECSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFECUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFECQty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblFEC))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFsCUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFsCSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFsCQty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblJC))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtJECUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtJECSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtJECQty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblJEC))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtJCUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtJCSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtJCQty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblFsC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Order Summary");

        jLblOrderTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblOrderTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLblOrderTotal.setText("Order Total");

        jLblDeliveryFee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblDeliveryFee.setForeground(new java.awt.Color(255, 255, 255));
        jLblDeliveryFee.setText("Delivery Fee");

        jtxtOrderTotal.setEditable(false);
        jtxtOrderTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtOrderTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtOrderTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtxtDeliveryFee.setEditable(false);
        jtxtDeliveryFee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDeliveryFee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtDeliveryFee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLblNetPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblNetPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLblNetPrice.setText("Net Price");

        jtxtNetPrice.setEditable(false);
        jtxtNetPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtNetPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtNetPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblOrderTotal)
                    .addComponent(jLblDeliveryFee)
                    .addComponent(jLblNetPrice))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtOrderTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtDeliveryFee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtNetPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblOrderTotal)
                    .addComponent(jtxtOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDeliveryFee)
                    .addComponent(jtxtDeliveryFee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNetPrice)
                    .addComponent(jtxtNetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        jBtnSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSubmit.setText("Submit");
        jBtnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSubmitMouseClicked(evt);
            }
        });
        jBtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitActionPerformed(evt);
            }
        });

        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnResetMouseClicked(evt);
            }
        });

        jLblTitle.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLblTitle.setText("Food Ordering System");

        jBtnConfirm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnConfirm.setText("Confirm");
        jBtnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConfirmMouseClicked(evt);
            }
        });
        jBtnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmActionPerformed(evt);
            }
        });

        jBtnLogout.setText("Logout");
        jBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jBtnSubmit)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnReset)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnConfirm)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnLogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTitle)
                    .addComponent(jBtnLogout))
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnResetMouseClicked
        jtxtOrderDate.setText(null);
        jtxtOrderTime.setText(null);

        jtxtFCQty.setText(null);
        jtxtFCSubTotal.setText(null);
        jtxtFCUnitPrice.setText(null);
        jtxtFECQty.setText(null);
        jtxtFECSubTotal.setText(null);
        jtxtFECUnitPrice.setText(null);
        jtxtFsCQty.setText(null);
        jtxtFsCSubTotal.setText(null);
        jtxtFsCUnitPrice.setText(null);
        jtxtJECQty.setText(null);
        jtxtJECSubTotal.setText(null);
        jtxtJECUnitPrice.setText(null);
        jtxtJCQty.setText(null);
        jtxtJCUnitPrice.setText(null);
        jtxtJCSubTotal.setText(null);

        jtxtOrderTotal.setText(null);
        jtxtDeliveryFee.setText(null);
        jtxtNetPrice.setText(null);
    }//GEN-LAST:event_jBtnResetMouseClicked

    private void jBtnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSubmitMouseClicked

    }//GEN-LAST:event_jBtnSubmitMouseClicked

    private void jBtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitActionPerformed
        //======================================== Date & Time ==============================================
        calendar = Calendar.getInstance();

        simpleDateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        jtxtOrderDate.setText(simpleDateFormat.format(calendar.getTime()));

        simpleTimeFormat = new SimpleDateFormat("HH:mm:ss");
        jtxtOrderTime.setText(simpleTimeFormat.format(calendar.getTime()));

        //======================================== Quantity ==============================================
        if (jtxtFCQty.getText().isEmpty()) {
            jtxtFCQty.setText("0");
        }
        Qty1 = Integer.parseInt(jtxtFCQty.getText());
        
        if (jtxtFECQty.getText().isEmpty()) {
            jtxtFECQty.setText("0");
        }
        Qty2 = Integer.parseInt(jtxtFECQty.getText());
        
        if (jtxtFsCQty.getText().isEmpty()) {
            jtxtFsCQty.setText("0");
        }
        Qty3 = Integer.parseInt(jtxtFsCQty.getText());
        
        if (jtxtJECQty.getText().isEmpty()) {
            jtxtJECQty.setText("0");
        }
        Qty4 = Integer.parseInt(jtxtJECQty.getText());
        
        if (jtxtJCQty.getText().isEmpty()) {
            jtxtJCQty.setText("0");
        }
        Qty5 = Integer.parseInt(jtxtJCQty.getText());

        //======================================== Unit Prices ==============================================
        String fried_Chicken = String.format("%.2f", orderProcess.getUnitPriceFriedChicken());
        jtxtFCUnitPrice.setText(fried_Chicken);

        String fried_Egg_Chicken = String.format("%.2f", orderProcess.getUnitPriceFriedEggChicken());
        jtxtFECUnitPrice.setText(fried_Egg_Chicken);

        String fries_Chicken = String.format("%.2f", orderProcess.getUnitPriceFriesChicken());
        jtxtFsCUnitPrice.setText(fries_Chicken);

        String jollof_Egg_Chicken = String.format("%.2f", orderProcess.getUnitPriceJollofEggChicken());
        jtxtJECUnitPrice.setText(jollof_Egg_Chicken);

        String jollof_Chicken = String.format("%.2f", orderProcess.getUnitPriceJollofChicken());
        jtxtJCUnitPrice.setText(jollof_Chicken);

        //======================================= Sub Total ==================================================
        sub1 = String.format("%.2f", Qty1 * orderProcess.getUnitPriceFriedChicken());
        jtxtFCSubTotal.setText(sub1);

        sub2 = String.format("%.2f", Qty2 * orderProcess.getUnitPriceFriedEggChicken());
        jtxtFECSubTotal.setText(sub2);

        sub3 = String.format("%.2f", Qty3 * orderProcess.getUnitPriceFriesChicken());
        jtxtFsCSubTotal.setText(sub3);

        sub4 = String.format("%.2f", Qty4 * orderProcess.getUnitPriceJollofEggChicken());
        jtxtJECSubTotal.setText(sub4);

        sub5 = String.format("%.2f", Qty5 * orderProcess.getUnitPriceJollofChicken());
        jtxtJCSubTotal.setText(sub5);

        //======================================= Total =========================================================
        double addAllSubTotal = (Qty1 * orderProcess.getUnitPriceFriedChicken())
                + (Qty2 * orderProcess.getUnitPriceFriedEggChicken())
                + (Qty3 * orderProcess.getUnitPriceFriesChicken())
                + (Qty4 * orderProcess.getUnitPriceJollofEggChicken())
                + (Qty5 * orderProcess.getUnitPriceJollofChicken());

        subTotal = String.format("%.2f", addAllSubTotal);
        jtxtOrderTotal.setText(subTotal);

        //======================================= Delivery Fee ==================================================
        delivery = String.format("%.2f", orderProcess.getDeliveryFee());
        jtxtDeliveryFee.setText(delivery);

        //======================================= Net Price ====================================================
        netTotal = String.format("%.2f", (addAllSubTotal + orderProcess.getDeliveryFee()));
        jtxtNetPrice.setText(netTotal);
    }//GEN-LAST:event_jBtnSubmitActionPerformed

    private void jBtnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConfirmMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmMouseClicked

    private void jBtnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmActionPerformed
        new Receipt_fds().setVisible(true);
    }//GEN-LAST:event_jBtnConfirmActionPerformed

    public static void getReceipt(JTextArea textArea) {
        textArea.append("\n\t         RECEIPT\n");
        textArea.append("===============================");
        textArea.append("\n\n\t               Order date:  " + simpleDateFormat.format(calendar.getTime()) + 
                        "\n\t               Order time:  " + simpleTimeFormat.format(calendar.getTime()));
        textArea.append("\n\nCustomer Name:         " + Login_fds.customerDetails.getFullName());
        textArea.append("\nCustomer Address:      " + Login_fds.customerDetails.getAddress());
        textArea.append("\nCustomer Phone No:    " + Login_fds.customerDetails.getPhoneNumber() + "\n\n");
        
        textArea.append("\nFood Item\t\tQuantity     Sub-Total\n");
        textArea.append("=======\t\t======   ======");
        textArea.append("\nFried Rice & Chicken\t     " + Qty1 + "\t" + sub1);
        textArea.append("\nFried Rice, Egg & Chicken\t     " + Qty2 + "\t" + sub2);
        textArea.append("\nFries & Chicken\t     " + Qty3 + "\t" + sub3);
        textArea.append("\nJollof Rice, Egg & Chicken\t     " + Qty4 + "\t" + sub4);
        textArea.append("\nJollof Rice & Chicken\t     " + Qty5 + "\t" + sub5 + "\n");
        textArea.append("\n\t\t   Order Total: " + subTotal);
        textArea.append("\n\t\t   Delivery Fee:   " + delivery + "\n");
        textArea.append("\n\n\t\t   Net Price: " + netTotal);
        textArea.append("\n\n\n\tThanks for your patronage!!!");
        
                
    }
    
    private void jBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogoutActionPerformed
        new Login_fds().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblAddress;
    private javax.swing.JLabel JLblCustomerAddress;
    private javax.swing.JLabel JLblCustomerName;
    private javax.swing.JLabel JLblCustomerPhoneNumber;
    private javax.swing.JLabel JLblName;
    private javax.swing.JButton jBtnConfirm;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblDeliveryFee;
    private javax.swing.JLabel jLblFC;
    private javax.swing.JLabel jLblFEC;
    private javax.swing.JLabel jLblFsC;
    private javax.swing.JLabel jLblItemType1;
    private javax.swing.JLabel jLblJC;
    private javax.swing.JLabel jLblJEC;
    private javax.swing.JLabel jLblNetPrice;
    private javax.swing.JLabel jLblOrderDate;
    private javax.swing.JLabel jLblOrderTime;
    private javax.swing.JLabel jLblOrderTotal;
    private javax.swing.JLabel jLblPhoneNo;
    private javax.swing.JLabel jLblQty;
    private javax.swing.JLabel jLblSubTotal;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JLabel jLblUnitPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jtxtDeliveryFee;
    private javax.swing.JTextField jtxtFCQty;
    private javax.swing.JTextField jtxtFCSubTotal;
    private javax.swing.JTextField jtxtFCUnitPrice;
    private javax.swing.JTextField jtxtFECQty;
    private javax.swing.JTextField jtxtFECSubTotal;
    private javax.swing.JTextField jtxtFECUnitPrice;
    private javax.swing.JTextField jtxtFsCQty;
    private javax.swing.JTextField jtxtFsCSubTotal;
    private javax.swing.JTextField jtxtFsCUnitPrice;
    private javax.swing.JTextField jtxtJCQty;
    private javax.swing.JTextField jtxtJCSubTotal;
    private javax.swing.JTextField jtxtJCUnitPrice;
    private javax.swing.JTextField jtxtJECQty;
    private javax.swing.JTextField jtxtJECSubTotal;
    private javax.swing.JTextField jtxtJECUnitPrice;
    private javax.swing.JTextField jtxtNetPrice;
    private javax.swing.JTextField jtxtOrderDate;
    private javax.swing.JTextField jtxtOrderTime;
    private javax.swing.JTextField jtxtOrderTotal;
    // End of variables declaration//GEN-END:variables
}
